management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /

server:
  port: 8080

logging:
  level:
    # These values override "logback.xml"
    root: ${LOGBACK_ROOT_LEVEL:-INFO}

config:
  logging:
    package: org.sample
    prefix: "Service configuration"